[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "handwriting-transformers"
version = "0.0.1"
description = "Handwriting Transformers"
authors = [
    { name = "Ankan Bhunia", email = "ankan.bhunia@gmail.com" },
]
dependencies = [
    "torch~=2.6",
    "torchvision~=0.21",
    "scipy~=1.15",
    "opencv-python-headless~=4.11",
    "Pillow~=11.2",
    "matplotlib~=3.10",
    "tqdm~=4.67",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
